# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriAnimal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('watershd_id', models.IntegerField()),
                ('Beef', models.IntegerField(default=0)),
                ('Dairy', models.IntegerField(default=0)),
                ('Swine', models.IntegerField(default=0)),
                ('Sheep', models.IntegerField(default=0)),
                ('Horse', models.IntegerField(default=0)),
                ('Chicken', models.IntegerField(default=0)),
                ('Turkey', models.IntegerField(default=0)),
                ('Duck', models.IntegerField(default=0)),
                ('numMonthsManureApplied', models.IntegerField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Animal', models.CharField(default=b'', max_length=30)),
                ('MassLb', models.FloatField(default=0)),
                ('BOD_per_1000lb', models.FloatField(default=0)),
                ('BOD_per_day', models.FloatField(default=0)),
                ('BDO_per_year', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWeightInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Animal', models.CharField(default=b'', max_length=30)),
                ('MassLb', models.FloatField(default=0)),
                ('BOD_per_1000lb', models.FloatField(default=0)),
                ('BOD_per_day', models.FloatField(default=0)),
                ('BDO_per_year', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BMPInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('session_id', models.IntegerField()),
                ('landtype_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
                ('BMP', models.IntegerField(default=0)),
                ('PercentApplied', models.FloatField(default=100)),
                ('N', models.FloatField(default=0)),
                ('P', models.FloatField(default=0)),
                ('BOD', models.FloatField(default=0)),
                ('Sediment', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('rmean', models.FloatField(null=True)),
                ('kmean', models.FloatField(null=True)),
                ('lsavg', models.FloatField(null=True)),
                ('cavg', models.FloatField(null=True)),
                ('pavg', models.FloatField(null=True)),
                ('state_name_name', models.CharField(max_length=30)),
                ('rainfall_inches', models.FloatField()),
                ('raindays', models.FloatField()),
                ('runoff', models.FloatField()),
                ('station_name', models.CharField(max_length=30, null=True)),
                ('ptrecipitation_correction_factor', models.FloatField(null=True)),
                ('no_of_rain_days_correction_factor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountyDataInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('rmean', models.FloatField(null=True)),
                ('kmean', models.FloatField(null=True)),
                ('lsavg', models.FloatField(null=True)),
                ('cavg', models.FloatField(null=True)),
                ('pavg', models.FloatField(null=True)),
                ('LocFileName', models.CharField(max_length=30)),
                ('LocName', models.CharField(max_length=30)),
                ('session_id', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedRunoff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SHG_A', models.IntegerField()),
                ('SHG_B', models.IntegerField()),
                ('SHG_C', models.IntegerField()),
                ('SHG_D', models.IntegerField()),
                ('Urban', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedRunoffInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SHG_A', models.IntegerField()),
                ('SHG_B', models.IntegerField()),
                ('SHG_C', models.IntegerField()),
                ('SHG_D', models.IntegerField()),
                ('Urban', models.CharField(max_length=30, db_index=True)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedlotAnimal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Animal', models.CharField(default=b'', max_length=30)),
                ('N', models.FloatField(default=0)),
                ('P', models.FloatField(default=0)),
                ('BOD', models.FloatField(default=0)),
                ('COD', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeedlotAnimalInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Animal', models.CharField(default=b'', max_length=30)),
                ('N', models.FloatField(default=0)),
                ('P', models.FloatField(default=0)),
                ('BOD', models.FloatField(default=0)),
                ('COD', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GullyErosion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SoilTexture', models.CharField(default=b'0', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('BMP_Efficiency', models.FloatField(default=0, choices=[(0, b'0 efficency'), (1, b'1 efficency')])),
                ('Years_to_Form', models.FloatField(default=0)),
                ('Length', models.FloatField(default=0)),
                ('Depth', models.FloatField(default=0)),
                ('Bottom_Width', models.FloatField(default=0)),
                ('Top_Width', models.FloatField(default=0)),
                ('Standard', models.CharField(unique=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GullyErosionInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SoilTexture', models.CharField(default=b'0', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('BMP_Efficiency', models.FloatField(default=0, choices=[(0, b'0 efficency'), (1, b'1 efficency')])),
                ('Years_to_Form', models.FloatField(default=0)),
                ('Length', models.FloatField(default=0)),
                ('Depth', models.FloatField(default=0)),
                ('Bottom_Width', models.FloatField(default=0)),
                ('Top_Width', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
                ('Gully_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_watershd', models.IntegerField()),
                ('num_gully', models.IntegerField()),
                ('num_steambank', models.IntegerField()),
                ('gwOpt', models.BooleanField(default=True)),
                ('swsOpt', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Cropland_Acres_Irrigated', models.FloatField(default=0)),
                ('Water_Depth_in_per_Irrigation_Before_BMP', models.FloatField(default=0)),
                ('Water_Depth_in_per_Irrigation_After_BMP', models.FloatField(default=0)),
                ('Irrigation_Frequency_perYear', models.FloatField(default=0)),
                ('Standard', models.CharField(unique=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrigationInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Cropland_Acres_Irrigated', models.FloatField(default=0)),
                ('Water_Depth_in_per_Irrigation_Before_BMP', models.FloatField(default=0)),
                ('Water_Depth_in_per_Irrigation_After_BMP', models.FloatField(default=0)),
                ('Irrigation_Frequency_perYear', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LanduseDistribution',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Commercial', models.FloatField(default=0)),
                ('Industrial', models.FloatField(default=0)),
                ('Institutional', models.FloatField(default=0)),
                ('Transportation', models.FloatField(default=0)),
                ('Multi_Family', models.FloatField(default=0)),
                ('Single_Family', models.FloatField(default=0)),
                ('Urban_Cultivated', models.FloatField(default=0)),
                ('Vacant_developed', models.FloatField(default=0)),
                ('Open_Space', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('Standard', models.CharField(unique=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanduseDistributionInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Commercial', models.FloatField(default=0)),
                ('Industrial', models.FloatField(default=0)),
                ('Institutional', models.FloatField(default=0)),
                ('Transportation', models.FloatField(default=0)),
                ('Multi_Family', models.FloatField(default=0)),
                ('Single_Family', models.FloatField(default=0)),
                ('Urban_Cultivated', models.FloatField(default=0)),
                ('Vacant_developed', models.FloatField(default=0)),
                ('Open_Space', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LateralRecessionRate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Category', models.CharField(default=b'', max_length=30)),
                ('LRR', models.CharField(default=b'', max_length=30)),
                ('Medium_Value', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LateralRecessionRateInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Category', models.CharField(default=b'', max_length=30)),
                ('LRR', models.CharField(default=b'', max_length=30)),
                ('Medium_Value', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NutrientGroundwaterRunoff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('BOD', models.FloatField()),
                ('Landuse', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientGroundwaterRunoffInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('BOD', models.FloatField()),
                ('Landuse', models.CharField(max_length=30, db_index=True)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NutrientRunoff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('BOD', models.FloatField()),
                ('Landuse', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientRunoffInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('BOD', models.FloatField()),
                ('Landuse', models.CharField(max_length=30, db_index=True)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRunoff',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SHG_A', models.IntegerField()),
                ('SHG_B', models.IntegerField()),
                ('SHG_C', models.IntegerField()),
                ('SHG_D', models.IntegerField()),
                ('Landuse', models.CharField(max_length=30)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRunoffInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SHG_A', models.IntegerField()),
                ('SHG_B', models.IntegerField()),
                ('SHG_C', models.IntegerField()),
                ('SHG_D', models.IntegerField()),
                ('Landuse', models.CharField(max_length=30, db_index=True)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SepticNillegal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('watershd_id', models.IntegerField()),
                ('numSepticSystems', models.IntegerField(default=0)),
                ('PopulationPerSeptic', models.IntegerField(default=0)),
                ('SepticFailureRate_Percent', models.IntegerField(default=0)),
                ('Wastewater_Direct_Discharge_numPeople', models.IntegerField(default=0)),
                ('Direct_Discharge_Reduction_Percent', models.IntegerField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SepticSystem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Title', models.CharField(default=b'', max_length=30)),
                ('ACR', models.FloatField(default=0)),
                ('Wastewater_per_capita', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SepticSystemInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Title', models.CharField(default=b'', max_length=30)),
                ('ACR', models.FloatField(default=0)),
                ('Wastewater_per_capita', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Soil_N_Conc', models.FloatField()),
                ('Soil_P_Conc', models.FloatField()),
                ('Soil_BOD_Conc', models.FloatField()),
                ('Standard', models.CharField(unique=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilDataInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Soil_N_Conc', models.FloatField()),
                ('Soil_P_Conc', models.FloatField()),
                ('Soil_BOD_Conc', models.FloatField()),
                ('session_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilInfiltrationFraction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('HSG', models.CharField(default=b'', max_length=30, db_index=True)),
                ('A', models.FloatField(default=0)),
                ('B', models.FloatField(default=0)),
                ('C', models.FloatField(default=0)),
                ('D', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SoilInfiltrationFractionInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('HSG', models.CharField(default=b'', max_length=30, db_index=True)),
                ('A', models.FloatField(default=0)),
                ('B', models.FloatField(default=0)),
                ('C', models.FloatField(default=0)),
                ('D', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilTexture',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Soil_Textural_Class', models.CharField(default=b'1', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('Dry_Density', models.FloatField(default=0)),
                ('Correction_Factor', models.FloatField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTextureInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Soil_Textural_Class', models.CharField(default=b'1', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('Dry_Density', models.FloatField(default=0)),
                ('Correction_Factor', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StreambankErosion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SoilTexture', models.CharField(default=b'0', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('BMP_Efficiency', models.FloatField(default=0, choices=[(0, b'0 efficency'), (1, b'1 efficency')])),
                ('Lateral_Recession', models.IntegerField(default=0, choices=[(1, b'Slight'), (2, b'Moderate'), (3, b'Severe'), (4, b'Very Severe')])),
                ('Height', models.FloatField(default=0)),
                ('Length', models.FloatField(default=0)),
                ('Standard', models.CharField(unique=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreambankErosionInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SoilTexture', models.CharField(default=b'0', max_length=30, choices=[(b'1', b'Clay'), (b'2', b'ClayLoam'), (b'3', b'FineSandyLoam'), (b'4', b'Loams,SandyClayLoams'), (b'5', b'Organic'), (b'6', b'Sands,LoamySands'), (b'7', b'SandyClay'), (b'8', b'SandyLoam'), (b'9', b'SiltLoam'), (b'10', b'SiltyClayLoam,SiltyClay')])),
                ('BMP_Efficiency', models.FloatField(default=0, choices=[(0, b'0 efficency'), (1, b'1 efficency')])),
                ('Lateral_Recession', models.IntegerField(default=0, choices=[(1, b'Slight'), (2, b'Moderate'), (3, b'Severe'), (4, b'Very Severe')])),
                ('Height', models.FloatField(default=0)),
                ('Length', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
                ('Streambank_id', models.IntegerField()),
                ('watershd_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversalSoilLossEquation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('watershd_id', models.IntegerField()),
                ('Cropland_R', models.FloatField(default=0)),
                ('Cropland_K', models.FloatField(default=0)),
                ('Cropland_LS', models.FloatField(default=0)),
                ('Cropland_C', models.FloatField(default=0)),
                ('Cropland_P', models.FloatField(default=0)),
                ('Pastureland_R', models.FloatField(default=0)),
                ('Pastureland_K', models.FloatField(default=0)),
                ('Pastureland_LS', models.FloatField(default=0)),
                ('Pastureland_C', models.FloatField(default=0)),
                ('Pastureland_P', models.FloatField(default=0)),
                ('Forest_R', models.FloatField(default=0)),
                ('Forest_K', models.FloatField(default=0)),
                ('Forest_LS', models.FloatField(default=0)),
                ('Forest_C', models.FloatField(default=0)),
                ('Forest_P', models.FloatField(default=0)),
                ('UserDefined_R', models.FloatField(default=0)),
                ('UserDefined_K', models.FloatField(default=0)),
                ('UserDefined_LS', models.FloatField(default=0)),
                ('UserDefined_C', models.FloatField(default=0)),
                ('UserDefined_P', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UrbanBmpInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('session_id', models.IntegerField()),
                ('key', models.CharField(max_length=30)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WatershedLandUse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('watershd_id', models.IntegerField()),
                ('HSG', models.IntegerField(default=1)),
                ('Urban', models.FloatField(default=0)),
                ('Cropland', models.FloatField(default=0)),
                ('Pastureland', models.FloatField(default=0)),
                ('Forest', models.FloatField(default=0)),
                ('UserDefined', models.FloatField(default=0)),
                ('Feedlots', models.FloatField(default=0)),
                ('FeedlotPercentPaved', models.IntegerField(default=20)),
                ('Total', models.FloatField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WildlifeDensityInCropLand',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Wildlife', models.CharField(default=b'', max_length=30)),
                ('NumPerMileSquare', models.IntegerField(default=0)),
                ('Standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WildlifeDensityInCropLandInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Wildlife', models.CharField(default=b'', max_length=30)),
                ('NumPerMileSquare', models.IntegerField(default=0)),
                ('session_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wildlifedensityincroplandinput',
            unique_together=set([('session_id', 'Wildlife')]),
        ),
        migrations.AlterUniqueTogether(
            name='wildlifedensityincropland',
            unique_together=set([('Standard', 'Wildlife')]),
        ),
        migrations.AlterUniqueTogether(
            name='watershedlanduse',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='urbanbmpinput',
            unique_together=set([('session_id', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='universalsoillossequation',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='streambankerosioninput',
            unique_together=set([('session_id', 'Streambank_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='soiltextureinput',
            unique_together=set([('session_id', 'Soil_Textural_Class')]),
        ),
        migrations.AlterUniqueTogether(
            name='soiltexture',
            unique_together=set([('Standard', 'Soil_Textural_Class')]),
        ),
        migrations.AlterUniqueTogether(
            name='soilinfiltrationfractioninput',
            unique_together=set([('session_id', 'HSG')]),
        ),
        migrations.AlterUniqueTogether(
            name='soilinfiltrationfraction',
            unique_together=set([('Standard', 'HSG')]),
        ),
        migrations.AlterUniqueTogether(
            name='soildatainput',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='septicsysteminput',
            unique_together=set([('session_id', 'Title')]),
        ),
        migrations.AlterUniqueTogether(
            name='septicsystem',
            unique_together=set([('Standard', 'Title')]),
        ),
        migrations.AlterUniqueTogether(
            name='septicnillegal',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='referencerunoffinput',
            unique_together=set([('session_id', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='referencerunoff',
            unique_together=set([('Standard', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='nutrientrunoffinput',
            unique_together=set([('session_id', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='nutrientrunoff',
            unique_together=set([('Standard', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='nutrientgroundwaterrunoffinput',
            unique_together=set([('session_id', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='nutrientgroundwaterrunoff',
            unique_together=set([('Standard', 'Landuse')]),
        ),
        migrations.AlterUniqueTogether(
            name='lateralrecessionrateinput',
            unique_together=set([('session_id', 'Category')]),
        ),
        migrations.AlterUniqueTogether(
            name='lateralrecessionrate',
            unique_together=set([('Standard', 'Category')]),
        ),
        migrations.AlterUniqueTogether(
            name='landusedistributioninput',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='irrigationinput',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='gullyerosioninput',
            unique_together=set([('session_id', 'Gully_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='feedlotanimalinput',
            unique_together=set([('session_id', 'Animal')]),
        ),
        migrations.AlterUniqueTogether(
            name='feedlotanimal',
            unique_together=set([('Standard', 'Animal')]),
        ),
        migrations.AlterUniqueTogether(
            name='detailedrunoffinput',
            unique_together=set([('session_id', 'Urban')]),
        ),
        migrations.AlterUniqueTogether(
            name='detailedrunoff',
            unique_together=set([('Standard', 'Urban')]),
        ),
        migrations.AlterUniqueTogether(
            name='countydata',
            unique_together=set([('state_name', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='bmpinput',
            unique_together=set([('session_id', 'landtype_id', 'watershd_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='animalweightinput',
            unique_together=set([('session_id', 'Animal')]),
        ),
        migrations.AlterUniqueTogether(
            name='animalweight',
            unique_together=set([('Standard', 'Animal')]),
        ),
        migrations.AlterUniqueTogether(
            name='agrianimal',
            unique_together=set([('session_id', 'watershd_id')]),
        ),
    ]
