# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepl', '0010_auto_20151005_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedrunoff',
            old_name='Landuse',
            new_name='Urban',
        ),
        migrations.RenameField(
            model_name='detailedrunoffinput',
            old_name='Landuse',
            new_name='Urban',
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Cropland_Acres_Irrigated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Irrigation_Frequency_perYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Water_Depth_in_per_Irrigation_After_BMP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='Water_Depth_in_per_Irrigation_Before_BMP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigationinput',
            name='Cropland_Acres_Irrigated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigationinput',
            name='Irrigation_Frequency_perYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigationinput',
            name='Water_Depth_in_per_Irrigation_After_BMP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='irrigationinput',
            name='Water_Depth_in_per_Irrigation_Before_BMP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Commercial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Industrial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Institutional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Multi_Family',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Open_Space',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Single_Family',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Transportation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Urban_Cultivated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistribution',
            name='Vacant_developed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Commercial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Industrial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Institutional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Multi_Family',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Open_Space',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Single_Family',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Transportation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Urban_Cultivated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landusedistributioninput',
            name='Vacant_developed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='detailedrunoffinput',
            unique_together=set([('session_id', 'Urban')]),
        ),
    ]
